-module(marvin_pdu_resume_tests).

-include("marvin_discord.hrl").
-include("marvin_pdu.hrl").
-include_lib("eunit/include/eunit.hrl").
-include_lib("marvin_helper/include/marvin_specs_tests.hrl").


-spec ?test_spec(test).

%% automatically generated by eunit


-spec ?test_spec(t01_can_get_new_test).

t01_can_get_new_test() ->
    marvin_pdu_resume:new(<<"token">>, <<"session_id">>, 100).


-spec ?test_spec(t02_can_get_fields_from_opaque_test).

t02_can_get_fields_from_opaque_test() ->
    PDU0 = marvin_pdu_resume:new(<<"token">>, <<"session_id">>, 100),
    ?assertEqual(<<"token">>, marvin_pdu_resume:token(PDU0)),
    ?assertEqual(<<"session_id">>, marvin_pdu_resume:session_id(PDU0)),
    ?assertEqual(100, marvin_pdu_resume:seq(PDU0)).


-spec ?test_spec(t03_can_set_fields_to_opaque_test).

t03_can_set_fields_to_opaque_test() ->
    PDU0 = marvin_pdu_resume:new(<<"token">>, <<"session_id">>, 100),
    PDU1 = marvin_pdu_resume:token(<<"another_token">>, PDU0),
    PDU2 = marvin_pdu_resume:session_id(<<"another_session_id">>, PDU1),
    PDU3 = marvin_pdu_resume:seq(200, PDU2),
    ?assertEqual(<<"another_token">>, marvin_pdu_resume:token(PDU3)),
    ?assertEqual(<<"another_session_id">>, marvin_pdu_resume:session_id(PDU3)),
    ?assertEqual(200, marvin_pdu_resume:seq(PDU3)).


-spec ?test_spec(t04_can_render_valid_opaque_test).

t04_can_render_valid_opaque_test() ->
    PDU0 = marvin_pdu_resume:new(<<"token">>, <<"session_id">>, 100),
    ?assertMatch({ok, _Message}, marvin_pdu:render(PDU0)).


-spec ?test_spec(t99_can_get_valid_parsed_test).

t99_can_get_valid_parsed_test() ->
    {ok, JSONBin} = file:read_file(
        code:priv_dir(marvin_pdu) ++ "/marvin_pdu_resume_test.json"),
    ?assertMatch({ok, {?marvin_pdu_resume(_), undefined}}, marvin_pdu:parse(JSONBin)).
