-module(marvin_pdu_dispatch_ready_tests).

-include("marvin_discord.hrl").
-include("marvin_pdu.hrl").
-include_lib("eunit/include/eunit.hrl").
-include_lib("marvin_helper/include/marvin_specs_tests.hrl").


-spec ?test_spec(test).

%% automatically generated by eunit


-spec ?test_spec(t01_can_get_new_test).

t01_can_get_new_test() ->
    Guilds = [
        marvin_pdu_object_guild_unavailable:new(100),
        marvin_pdu_object_guild_unavailable:new(200),
        marvin_pdu_object_guild_unavailable:new(300)
    ],
    PrivateChannels = [
        marvin_pdu_object_channel_dm:new(
            100, 1, 200, [marvin_pdu_object_user:new(
                100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        ),
        marvin_pdu_object_channel_dm:new(
            200, 1, 300, [marvin_pdu_object_user:new(
                200, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        )
    ],
    User = marvin_pdu_object_user:new(
        100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
        false, true, true, <<"nobody@nowhere.com">>
    ),
    marvin_pdu_dispatch_ready:new(
        Guilds, [], PrivateChannels, [], <<"session-id">>, [0,1], User, #{}, 6
    ).


-spec ?test_spec(t02_can_get_fields_from_opaque_test).

t02_can_get_fields_from_opaque_test() ->
    Guilds = [
        marvin_pdu_object_guild_unavailable:new(100),
        marvin_pdu_object_guild_unavailable:new(200),
        marvin_pdu_object_guild_unavailable:new(300)
    ],
    PrivateChannels = [
        marvin_pdu_object_channel_dm:new(
            100, 1, 200, [marvin_pdu_object_user:new(
                100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        ),
        marvin_pdu_object_channel_dm:new(
            200, 1, 300, [marvin_pdu_object_user:new(
                200, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        )
    ],
    User = marvin_pdu_object_user:new(
        100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
        false, true, true, <<"nobody@nowhere.com">>
    ),
    PDU0 = marvin_pdu_dispatch_ready:new(
        Guilds, [], PrivateChannels, [], <<"session-id">>, [0,1], User, #{}, 6
    ),
    ?assertEqual(Guilds, marvin_pdu_dispatch_ready:guilds(PDU0)),
    ?assertEqual([], marvin_pdu_dispatch_ready:presences(PDU0)),
    ?assertEqual(PrivateChannels, marvin_pdu_dispatch_ready:private_channels(PDU0)),
    ?assertEqual([], marvin_pdu_dispatch_ready:relationships(PDU0)),
    ?assertEqual(<<"session-id">>, marvin_pdu_dispatch_ready:session_id(PDU0)),
    ?assertEqual([0,1], marvin_pdu_dispatch_ready:shard(PDU0)),
    ?assertEqual(User, marvin_pdu_dispatch_ready:user(PDU0)),
    ?assertEqual(#{}, marvin_pdu_dispatch_ready:user_settings(PDU0)),
    ?assertEqual(6, marvin_pdu_dispatch_ready:v(PDU0)).


-spec ?test_spec(t03_can_set_fields_to_opaque_test).

t03_can_set_fields_to_opaque_test() ->
    Guilds = [
        marvin_pdu_object_guild_unavailable:new(100),
        marvin_pdu_object_guild_unavailable:new(200),
        marvin_pdu_object_guild_unavailable:new(300)
    ],
    PrivateChannels = [
        marvin_pdu_object_channel_dm:new(
            100, 1, 200, [marvin_pdu_object_user:new(
                100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        ),
        marvin_pdu_object_channel_dm:new(
            200, 1, 300, [marvin_pdu_object_user:new(
                200, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        )
    ],
    User = marvin_pdu_object_user:new(
        100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
        false, true, true, <<"nobody@nowhere.com">>
    ),
    PDU0 = marvin_pdu_dispatch_ready:new(1, 2, 3, 4, 5, 6, 7, 8, 9),
    PDU1 = marvin_pdu_dispatch_ready:guilds(Guilds, PDU0),
    PDU2 = marvin_pdu_dispatch_ready:presences([], PDU1),
    PDU3 = marvin_pdu_dispatch_ready:private_channels(PrivateChannels, PDU2),
    PDU4 = marvin_pdu_dispatch_ready:relationships([], PDU3),
    PDU5 = marvin_pdu_dispatch_ready:session_id(<<"session-id">>, PDU4),
    PDU6 = marvin_pdu_dispatch_ready:shard([0,1], PDU5),
    PDU7 = marvin_pdu_dispatch_ready:user(User, PDU6),
    PDU8 = marvin_pdu_dispatch_ready:user_settings(#{}, PDU7),
    PDU9 = marvin_pdu_dispatch_ready:v(6, PDU8),
    ?assertEqual(Guilds, marvin_pdu_dispatch_ready:guilds(PDU9)),
    ?assertEqual([], marvin_pdu_dispatch_ready:presences(PDU9)),
    ?assertEqual(PrivateChannels, marvin_pdu_dispatch_ready:private_channels(PDU9)),
    ?assertEqual([], marvin_pdu_dispatch_ready:relationships(PDU9)),
    ?assertEqual(<<"session-id">>, marvin_pdu_dispatch_ready:session_id(PDU9)),
    ?assertEqual([0,1], marvin_pdu_dispatch_ready:shard(PDU9)),
    ?assertEqual(User, marvin_pdu_dispatch_ready:user(PDU9)),
    ?assertEqual(#{}, marvin_pdu_dispatch_ready:user_settings(PDU9)),
    ?assertEqual(6, marvin_pdu_dispatch_ready:v(PDU9)).


-spec ?test_spec(t04_can_render_valid_opaque_test).

t04_can_render_valid_opaque_test() ->
    Guilds = [
        marvin_pdu_object_guild_unavailable:new(100),
        marvin_pdu_object_guild_unavailable:new(200),
        marvin_pdu_object_guild_unavailable:new(300)
    ],
    PrivateChannels = [
        marvin_pdu_object_channel_dm:new(
            100, 1, 200, [marvin_pdu_object_user:new(
                100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        ),
        marvin_pdu_object_channel_dm:new(
            200, 1, 300, [marvin_pdu_object_user:new(
                200, <<"user">>, <<"1337">>, <<"some-long-hash">>,
                false, true, true, <<"nobody@nowhere.com">>
            )]
        )
    ],
    User = marvin_pdu_object_user:new(
        100, <<"user">>, <<"1337">>, <<"some-long-hash">>,
        false, true, true, <<"nobody@nowhere.com">>
    ),
    PDU0 = marvin_pdu_dispatch_ready:new(
        Guilds, [], PrivateChannels, [], <<"session-id">>, [0,1], User, #{}, 6
    ),
    ?assertMatch({ok, _Message}, marvin_pdu:render(PDU0)).


-spec ?test_spec(t99_can_get_valid_parsed_test).

t99_can_get_valid_parsed_test() ->
    {ok, JSONBin} = file:read_file(
        code:priv_dir(marvin_pdu) ++ "/marvin_pdu_dispatch_ready_test.json"),
    ?assertMatch({ok, {?marvin_pdu_dispatch_ready(_), 1}}, marvin_pdu:parse(JSONBin)).
